Repository ml4ai/ASKEM-TA1-DockerVM, pull requests merged in 2023-06, with the labels that each got.

#17 End to end examples for SKEMA workflows (WIP)
  .gitignore
  code2fn-rest/.gitkeep
  code2fn-rest/data/.gitkeep
  code2fn-rest/docker-compose.yml
  code2fn-rest/notebooks/.gitkeep
  data/.gitkeep
  end-to-end-rest/.gitkeep
  end-to-end-rest/README.md
  end-to-end-rest/data/code/CHIME_SIR_core.py
  end-to-end-rest/data/code/cpktkm.f95
  end-to-end-rest/data/images/bayes-rule-white-bg.png
  end-to-end-rest/data/images/sidarthe_eqn1.png
  end-to-end-rest/data/images/sidarthe_eqn2.png
  end-to-end-rest/data/images/sidarthe_eqn3.png
  end-to-end-rest/data/images/sidarthe_eqn4.png
  end-to-end-rest/data/images/sidarthe_eqn5.png
  end-to-end-rest/data/images/sidarthe_eqn6.png
  end-to-end-rest/data/images/sidarthe_eqn7.png
  end-to-end-rest/data/images/sidarthe_eqn8.png
  end-to-end-rest/data/latex/sidarthe_eqn1.txt
  end-to-end-rest/data/latex/sidarthe_eqn2.txt
  end-to-end-rest/data/latex/sidarthe_eqn3.txt
  end-to-end-rest/data/latex/sidarthe_eqn4.txt
  end-to-end-rest/data/latex/sidarthe_eqn5.txt
  end-to-end-rest/data/latex/sidarthe_eqn6.txt
  end-to-end-rest/data/latex/sidarthe_eqn7.txt
  end-to-end-rest/data/latex/sidarthe_eqn8.txt
  end-to-end-rest/docker-compose.yml
  end-to-end-rest/notebooks/e2e.ipynb
  equations-rest/.gitkeep
  equations-rest/README.md
  equations-rest/docker-compose.yml
  equations-rest/eq2mml.py
  equations-rest/notebooks/equations_rest.ipynb
  equations-rest/notebooks/run_mathjax_server.ipynb
  morae-demo/.gitkeep
  morae-demo/MORAE_demo.ipynb
  morae-demo/data/.DS_Store
  morae-demo/data/lotka_voltera/mml_list.txt
  morae-demo/data/simple_sir_v1/mml_list.txt
  morae-demo/data/sir_core--Gromet-FN-auto.json
  morae-demo/start_skema_rust_service.ipynb
  text-reading-batch/.gitkeep
  text-reading-batch/notebooks/.gitkeep
  text-reading-rest/.gitkeep
  text-reading-rest/notebooks/.gitkeep
Labels: Integration

#21 Code2fn system services description
  end-to-end-rest/data/code/CHIME_SIR.py
  end-to-end-rest/data/code/exp1.f95
  end-to-end-rest/data/code/exp1.py
  end-to-end-rest/notebooks/e2e.ipynb
Labels: documentation, Integration

#23 Adding example call to code2fn zip endpoint
  end-to-end-rest/data/code/system_test/driver.py
  end-to-end-rest/data/code/system_test/model.py
  end-to-end-rest/data/code/system_test/system_filepaths.txt
  end-to-end-rest/data/code/system_test/util/util.py
  end-to-end-rest/notebooks/e2e.ipynb
Labels: documentation

#13 Adds code2fn Jupyter notebooks
  end-to-end-rest/notebooks/code2fn/fn-given-filepaths-zip.ipynb
  end-to-end-rest/notebooks/code2fn/fn-given-filepaths.ipynb
  end-to-end-rest/notebooks/code2fn/system_test.zip
  end-to-end-rest/notebooks/code2fn/system_test/driver.py
  end-to-end-rest/notebooks/code2fn/system_test/model.py
  end-to-end-rest/notebooks/code2fn/system_test/system_filepaths.txt
  end-to-end-rest/notebooks/code2fn/system_test/util/util.py
Labels: documentation

#15 TextReading Integration Notebook
  end-to-end-rest/README.md
  end-to-end-rest/docker-compose.yml
  end-to-end-rest/notebooks/e2e.ipynb
  end-to-end-rest/notebooks/text_reading/1-s2.0-S2211379721005490-main.txt
  end-to-end-rest/notebooks/text_reading/text_reading_pipeline.ipynb
  legacy/Dockerfile
  legacy/README.md
  legacy/client.sh
  legacy/docker-compose.yml
  legacy/inputs/1-s2.0-S2211379721005490-main.txt
  outputs/canonical_1-s2.0-S2211379721005490-main.json
Labels: enhancement
